
    create table bloqueo_operativo (
        fecha_fin date not null,
        fecha_inicio date not null,
        bloqueo_id bigint generated by default as identity,
        medico_id bigint not null,
        motivo varchar(255) not null,
        tipo varchar(255) not null,
        primary key (bloqueo_id)
    );

    create table disponibilidad (
        fecha_fin date not null,
        fecha_inicio date not null,
        hora_fin time(6) not null,
        hora_inicio time(6) not null,
        disponibilidad_id bigint generated by default as identity,
        medico_id bigint not null,
        primary key (disponibilidad_id)
    );

    create table disponibilidad_dias (
        disponibilidad_id bigint not null,
        dia varchar(255)
    );

    create table especialidad (
        especialidad_id bigint generated by default as identity,
        descripcion varchar(255),
        especialidad varchar(255) not null,
        primary key (especialidad_id)
    );

    create table medico (
        especialidad_id bigint not null,
        medico_id bigint generated by default as identity,
        rol_id bigint not null,
        apellido varchar(255),
        email varchar(255) not null unique,
        nombre varchar(255),
        numero_documento varchar(255) not null unique,
        password varchar(255) not null,
        tipo_documento varchar(255) not null,
        primary key (medico_id)
    );

    create table notificacion (
        fecha time(6) not null,
        bloqueo_id bigint not null,
        notificacion_id bigint generated by default as identity,
        mensaje varchar(255) not null,
        primary key (notificacion_id)
    );

    create table rol (
        rol_id bigint generated by default as identity,
        nombre varchar(255) not null,
        permisos varchar(255) not null,
        primary key (rol_id)
    );

    alter table if exists bloqueo_operativo 
       add constraint FKgfmee4s12t2kim4uk6qg0eem1 
       foreign key (medico_id) 
       references medico;

    alter table if exists disponibilidad 
       add constraint FKdwpijofaog4b926f5nbirepul 
       foreign key (medico_id) 
       references medico;

    alter table if exists disponibilidad_dias 
       add constraint FKp4yqwhi6sg56nbyxp4aj9ehgf 
       foreign key (disponibilidad_id) 
       references disponibilidad;

    alter table if exists medico 
       add constraint FKqvv5xs5qs7xbhvu93a7wj3lhb 
       foreign key (especialidad_id) 
       references especialidad;

    alter table if exists medico 
       add constraint FK28aoejrwf22u44iubhkdhek74 
       foreign key (rol_id) 
       references rol;

    alter table if exists notificacion 
       add constraint FKqvk46mfea6ft5fpn5ubac205g 
       foreign key (bloqueo_id) 
       references bloqueo_operativo;
