# render.yaml (Versión final y recomendada)

services:
  # Define el servicio web para tu backend de Spring Boot
  - type: web
    name: backend-citasalud
    env: docker
    plan: free
    healthCheckPath: /actuator/health

    # Variables de entorno
    envVars:
      # --- Conexión a la Base de Datos (gestionada por Render) ---
      - key: DB_URL
        fromDatabase:
          name: cita_salud
          property: internalConnectionString
      - key: DB_USERNAME
        fromDatabase:
          name: cita_salud
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cita_salud
          property: password

      # --- Secretos (gestionados manualmente en el Dashboard de Render) ---
      - key: JWT_SECRET
        sync: false # No sincroniza el valor con el repositorio Git
      - key: JWT_EXPIRATION
        sync: false # No sincroniza el valor con el repositorio Git
    runtime:

  # Define la base de datos PostgreSQL que tu servicio necesita
  - type: psql
    name: cita_salud # El nombre que usamos para referenciarla arriba
    plan: free