# render.yaml (Corregido con el tipo 'psql' y la indentación correcta)

services:
  # 1. Servicio Web para el backend
  - type: web
    name: backend-citasalud
    env: docker
    plan: free
    healthCheckPath: /actuator/health

    envVars:
      - key: DB_URL
        fromDatabase:
          name: cita-salud-db # Usamos el nuevo nombre para evitar conflictos
          property: internalConnectionString
      - key: DB_USERNAME
        fromDatabase:
          name: cita-salud-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cita-salud-db
          property: password

      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        sync: false

  # 2. Servicio de Base de Datos PostgreSQL
  - type: psql # <-- CORREGIDO: El tipo correcto es 'psql'
    name: cita-salud-db # Le damos un nombre único para la base de datos
    plan: free