services:
  - type: web
    name: backend-citasalud
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        fromDatabase:
          name: cita-salud-db
          property: internalConnectionString
      - key: DB_USERNAME
        fromDatabase:
          name: cita-salud-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cita-salud-db
          property: password
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        sync: false

  - type: psql
    name: cita-salud-db
    plan: free