# render.yaml (Corregido con el tipo de base de datos correcto)

services:
  # Define el servicio web para tu backend de Spring Boot
  - type: web
    name: backend-citasalud
    env: docker
    plan: free
    healthCheckPath: /actuator/health

    envVars:
      # --- Conexión a la Base de Datos (gestionada por Render) ---
      - key: DB_URL
        fromDatabase:
          name: cita_salud
          property: internalConnectionString
      - key: DB_USERNAME
        fromDatabase:
          name: cita_salud
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cita_salud
          property: password

      # --- Secretos (gestionados manualmente en el Dashboard de Render) ---
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        sync: false

  # Define la base de datos PostgreSQL que tu servicio necesita
  - type: db # <-- CORREGIDO: El tipo correcto es 'db'
    name: cita_salud
    databaseName: cita_salud_db # Nombre real de la base de datos interna
    user: citasalud_user # Nombre del usuario que se creará
    plan: free