# docker-compose.yml (GUARDAR en la carpeta 'monitoring')

services:
  backend:
    image: citasalud-backend:1.0 # ¡Asegúrate de que este nombre y etiqueta coincidan con tu imagen!
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:postgresql://dpg-d0t7osm3jp1c73ea5c50-a.oregon-postgres.render.com/cita_salud"
      DB_USERNAME: "postgres" # <-- CORREGIDO: 'postgres' con una sola 's'
      DB_PASSWORD: "N2M2XB7EwxWgJoU6qkKQhYtCtt3SmqRN"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage: